spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/SEPA_RATE?useSSL=false
    username: root
    password: password
    continueOnError: true
    hibernate:
      ddl-auto: none
#    driver-class-name: oracle.jdbc.OracleDriver


keycloak:
  realm: "master"
  auth-server-url: http://localhost:8880/auth
  ssl-required: external
  resource: SpringBootClient
  public-client: true
  confidential-port: 0
